name: Go

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  setup:
    runs-on: [ubuntu-latest]
    steps:
      - uses: 1ng3n/init-ci@master
  build:
    needs: [setup]
    runs-on: ${{ needs.setup.outputs.runner }}
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
    
    - uses: 1ng3n/setup-chrome@master
      with:
        chrome-version: beta
    - run: chrome --version
